### ISSUE TITLE
About PermanentMountainChallenge, after stage Mountain Shrines become infinitely usable

### ISSUE THREAD

**Issue by ayykiri** [khouryj/VoidItemAPI#1]
i didnt know where else to tell you this, since there doesnt seem to be a github for the permanent mountain challenge mod, so i will tell you the issue here, at least for now:

if you use a mountain shrine in any stage it works normally, any mountain shrine in any stage after becomes infinitely usable
https://youtu.be/EtNheDifG6U

**Comment by ayykiri** [comment]
actually it puts another stack EACH FRAME you hold the interact key

**Comment by khouryj** [comment]
Hi, I am unsure of what might be causing this issue. Is it possible for you to send me a log file of the incident? You can reach me much easier if you are on the modding discord server joseph#6783, or attaching it here works as well.

**Comment by ayykiri** [comment]
Which log file would you like? I only know of the BepInEx log file but that only logs the game launch. And this glitch is only during gameplay.

**Comment by khouryj** [comment]
The BepInEx log file is the one I need, it should be storing logs of your gameplay as well.

**Comment by ayykiri** [comment]
https://drive.google.com/file/d/1sGF1rR2jjpAhqiVz8uMb3I5G464psgF2/view?usp=sharing
(at the end there's a lot of errors with 12 lines each roughly about shrine stacks and a different mod)
it seems actually that it's a bug with a mod called WolfoQualityOfLife
will report again after i have checked this problem without that mod

**Comment by ayykiri** [comment]
yeah that mod breaks this mod. will have to speak with that mod's developer, since the errors in the log only mention his log
i guess this can be closed now
